//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario_MinisterioAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambio_designacion
    {
        public int Id_designacion { get; set; }
        public string Nombre_Completo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Cedula { get; set; }
        public Nullable<int> Id_Cargo_Actual { get; set; }
        public Nullable<int> Id_Cargo_Nuevo { get; set; }
        public decimal Salario_Propuesto { get; set; }
        public Nullable<int> Id_Departamento_Propuesto { get; set; }
        public string Referido_por { get; set; }
        public string Observaciones { get; set; }
        public string Estatus { get; set; }
        public byte[] Archivo { get; set; }
        public string Extension { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Cargo Cargo1 { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
